// Generates src/components/icons/solar-data.ts with only the Solar icons the
// console uses, so no icon JSON or network fetch ships to the browser.
// Run: node scripts/gen-icons.mjs   (re-run after adding names below)
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const set = JSON.parse(readFileSync(require.resolve("@iconify-json/solar/icons.json"), "utf8"));

export const NAMES = [
  // navigation
  "widget-5-bold-duotone",
  "calendar-mark-bold-duotone",
  "clock-circle-bold-duotone",
  "buildings-2-bold-duotone",
  "notebook-bookmark-bold-duotone",
  "square-academic-cap-bold-duotone",
  "smartphone-2-bold-duotone",
  "users-group-rounded-bold-duotone",
  "bell-bing-bold-duotone",
  "chart-2-bold-duotone",
  "shield-user-bold-duotone",
  "clipboard-list-bold-duotone",
  "settings-bold-duotone",
  "crown-bold-duotone",
  // features, empty states, roles
  "user-rounded-bold-duotone",
  "user-id-bold-duotone",
  "calendar-add-bold-duotone",
  "videocamera-record-bold-duotone",
  "map-point-bold-duotone",
  "case-round-bold-duotone",
  "square-academic-cap-2-bold-duotone",
  "inbox-line-bold-duotone",
  "checklist-minimalistic-bold-duotone",
  "magnifer-bold-duotone",
  "danger-triangle-bold-duotone",
  "lock-keyhole-minimalistic-bold-duotone",
  "letter-bold-duotone",
  "key-minimalistic-2-bold-duotone",
  "logout-3-bold-duotone",
  "star-bold-duotone",
  "graph-up-bold-duotone",
  "document-add-bold-duotone",
  "gallery-wide-bold-duotone",
  "database-bold-duotone",
  "sun-2-bold-duotone",
  "moon-bold-duotone",
  "monitor-bold-duotone",
  "shield-check-bold-duotone",
  "user-plus-rounded-bold-duotone",
  "hashtag-square-bold-duotone",
];

const missing = NAMES.filter((n) => !set.icons[n] && !set.aliases?.[n]);
if (missing.length) {
  console.error("Missing Solar icons:", missing.join(", "));
  process.exit(1);
}
const body = (n) => (set.icons[n] ?? set.icons[set.aliases[n].parent]).body;
const out = `// AUTO-GENERATED by scripts/gen-icons.mjs from @iconify-json/solar (CC BY 4.0). Do not edit.
export const SOLAR = {
${NAMES.map((n) => `  ${JSON.stringify(n)}: ${JSON.stringify(body(n))},`).join("\n")}
} as const;
export type SolarName = keyof typeof SOLAR;
`;
mkdirSync("src/components/icons", { recursive: true });
writeFileSync("src/components/icons/solar-data.ts", out);
console.log(`Wrote ${NAMES.length} icons`);
